name: Construir imagen y subirla a Docker Hub

on: 
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              uses: docker/setup-buildx-action@v2

            - name: Push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: 
                    ${{ secrets.DOCKER_USERNAME }}/docker-github-actions:latest
                    ${{ secrets.DOCKER_USERNAME }}/docker-github-actions:${{ github.sha }}
                    
